### ISSUE TITLE
sorry, i have a issue

### ISSUE THREAD

**Issue by mathpopo** [andrew-hardin/cmake-fortify-demo#1]
hi ,first thank you for you great job,but i use it ,meet some issue
![1146897822](https://user-images.githubusercontent.com/21274466/171796908-d04d80af-8ee6-4a19-9fb6-f30957f1e420.jpg)
,

**Comment by mathpopo** [comment]
i use 21.2.2 versiion, is my version error?

**Comment by mathpopo** [comment]
https://community.microfocus.com/cyberres/fortify/f/fortify-discussions/5498/fortify-giving-error-unrecognized-or-invalid-command-line-argument--o

**Comment by andrew-hardin** [comment]
I don't see any obvious signs that point to what's going wrong. The `fortify/shim/cxx` file create by the build system is a thin pass through to Fortify. It's strange that fortify is saying it doesn't recognize the `-o` option... maybe try one of the built-in Fortify C++ examples and verify the software is installed correctly?
